# Generated by Django 5.0 on 2023-12-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('repo', models.URLField(verbose_name='Link to Repo')),
                ('link_if_deployed', models.URLField(verbose_name='Link to Deployed App')),
                ('image', models.FileField(blank=True, upload_to='project_images/')),
            ],
        ),
    ]
