services:
  backend:
    build:
      context: ./backend
    command: gunicorn portfolio_website.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/dist
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  frontend_build:
