services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules

volumes:
  node_modules:
