services:
  # Django Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - portfolio_static:/home/backend/django/staticfiles
      - portfolio_media:/home/backend/django/mediafiles
    user: "backend:backend_group"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vite React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: portfolio-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portfolio_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portfolio-website/static
  portfolio_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portfolio-website/media

networks:
  default:
    name: portfolio_network
    external: true
