services:
  # Django Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - /opt/portfolio-website/backend/static:/home/backend/django/staticfiles
      - /opt/portfolio-website/backend/media:/home/backend/django/mediafiles
    user: "backend:backend_group"
    expose:
      - "4040"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://portfolio-backend:4040/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Vite React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: portfolio-frontend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    ports:
      - "4000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://portfolio-frontend:80/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

#Volumes & Networks
volumes:
  postgres_data:
networks:
  default:
    name: portfolio_network
    external: true
