services:
  # PostgreSQL Database Service
  db:
    image: postgres:17-alpine
    container_name: portfolio-db
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_DB: portfolio-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-backend

  # Django Backend Service
  backend:
    build:
      context: ./backend # Assuming Django files are in 'backend' directory
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000" # Expose port 8000 for Django
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./backend:/portfolio_website
    expose:
      - "8000"

  # Vite React Frontend Service
  frontend:
    build: ./frontend # Assuming Vite files are in 'frontend' directory
    container_name: portfolio-frontend
    restart: unless-stopped
    networks:
      - frontend
    expose:
      - "80"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
