services:
  # Django Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend:/home/backend/react
      - /var/www/django_static:/home/backend/react/static
      - /var/www/django_media:/home/backend/react/media
    user: "backend:backend_group"
    ports:
      - "4040:4040"

  # PostgreSQL Database Service
  db:
    image: postgres:17-alpine
    container_name: portfolio-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRESQL_DB}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Vite React Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: portfolio-frontend
    user: "frontend:frontend_group"
    restart: unless-stopped
    ports:
      - "4000:80"

volumes:
  postgres_data:
