services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - portfolio_static:/home/backend/django/staticfiles
      - portfolio_media:/home/backend/django/mediafiles
      - portfolio_logs:/home/backend/django/logs
    user: "backend:backend_group"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: portfolio-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://portfolio-api.rajivwallace.com # Single nginx endpoint
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Single unified nginx service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: portfolio-nginx
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - portfolio_static:/usr/share/nginx/html/static:ro
      - portfolio_media:/usr/share/nginx/html/media:ro
      - portfolio_logs:/var/log/nginx
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  portfolio_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portfolio-website/static

  portfolio_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portfolio-website/media

  portfolio_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portfolio-website/logs

networks:
  default:
    name: portfolio_network
    external: true
