FROM python:3.12-slim

WORKDIR /backend

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBFFERED 1

RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn", "portfolio_website.wsgi:application","--bind", "0.0.0.0:8000". "--workers", "4"]