# Generated by Django 5.0 on 2024-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_if_deployed',
            field=models.URLField(blank=True, verbose_name='Link to Deployed App'),
        ),
    ]
