# Generated by Django 5.2.6 on 2026-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_tag_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Tailwind color classes for project switcher",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="emoji",
            field=models.CharField(
                blank=True, help_text="Emoji icon for project switcher", max_length=10
            ),
        ),
    ]
