# Generated by Django 5.2.6 on 2026-06-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_color_project_emoji"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="color",
        ),
        migrations.AddField(
            model_name="project",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to show or hide this project from the public API.",
            ),
        ),
    ]
