# Generated by Django 5.1.6 on 2025-02-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link_if_deployed',
            new_name='deployed_url',
        ),
    ]
