# Generated by Django 5.0 on 2023-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('referral_link', models.URLField(verbose_name='Referral Link')),
                ('image', models.FileField(blank=True, upload_to='wallet_images/')),
            ],
        ),
    ]
