# Generated by Django 5.0 on 2024-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='referral_link',
            field=models.URLField(blank=True, verbose_name='Referral Link'),
        ),
    ]
