# Generated by Django 5.0 on 2024-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_card_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='annual_fee',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
