# Generated by Django 5.0 on 2024-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_card_annual_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='annual_fee',
            field=models.CharField(blank=True, max_length=20, verbose_name='Annual Fee'),
        ),
    ]
