# Generated by Django 5.0 on 2024-04-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_card_annual_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='wallet_images/'),
        ),
    ]
