# Generated by Django 5.2.6 on 2025-10-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_header', models.CharField(default='Portfolio Website', help_text='Site Header - Full Name, Site Title, etc.', max_length=100)),
                ('professional_title', models.CharField(default='Software Developer', help_text='Professional Title (displayed under Site Header)', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('greeting', models.CharField(default='Hello!', help_text='Homepage Greeting', max_length=100)),
                ('bio', models.TextField(help_text='Bio')),
                ('github', models.URLField(blank=True, help_text='GitHub Profile URL (optional)', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Linkedin Profile URL (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Information',
                'verbose_name_plural': 'Profile Information',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one resume can be active at a time')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
