# Generated by Django 5.0 on 2023-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'bio',
            },
        ),
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'linkedIn',
            },
        ),
        migrations.CreateModel(
            name='TwitterX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'twitter',
            },
        ),
    ]
