# Generated by Django 5.0 on 2023-12-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_github_linkedin_twitterx_delete_profilelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterX',
        ),
    ]
