# Generated by Django 5.2.6 on 2026-06-08 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0003_globallink_short_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrandAsset",
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="SkillCategory",
        ),
    ]
