# Generated by Django 5.0 on 2024-02-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_delete_twitterx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('github', models.URLField()),
                ('linkedIn', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'info',
            },
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.DeleteModel(
            name='GitHub',
        ),
        migrations.DeleteModel(
            name='LinkedIn',
        ),
    ]
