# Generated by Django 5.2.6 on 2026-06-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_delete_brandasset_delete_certification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='GlobalLink',
        ),
    ]
