# Generated by Django 5.0 on 2024-04-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_rename_body_info_bio_info_favicon_info_greeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='favicon',
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='info_images/'),
        ),
    ]
