# Generated by Django 5.1.6 on 2025-02-08 19:33

import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_info_favicon_alter_info_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for this version of your resume', max_length=100)),
                ('file', models.FileField(help_text='Upload your resume in PDF format (max 5MB)', upload_to='resumes/%Y/%m/', validators=[info.models.validate_pdf])),
                ('is_active', models.BooleanField(default=True, help_text='Only one resume can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this resume')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
