# Generated by Django 5.1.6 on 2025-02-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
    ]
