# Generated by Django 5.1.6 on 2025-02-18 15:48

import info.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_resume_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='version',
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(help_text='Upload a PDF file (max 5MB)', upload_to='resumes/', validators=[info.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
