# Generated by Django 5.1.6 on 2025-02-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'resume Uploads'},
        ),
    ]
