# Generated by Django 5.1.6 on 2025-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_resume_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='info/photos'),
        ),
    ]
