# Generated by Django 5.2.6 on 2025-09-17 21:39

import django.utils.timezone
import info.models
import info.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_info_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profile Information', 'verbose_name_plural': 'Profile Information'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resume Uploads'},
        ),
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='filename',
            field=models.CharField(blank=True, help_text='Original filename for reference', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(help_text='Biography or description text'),
        ),
        migrations.AlterField(
            model_name='info',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='greeting',
            field=models.CharField(default='Hello!', help_text='Greeting message displayed on the homepage', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedIn',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG, PNG, GIF, or WebP, max 10MB)', null=True, upload_to=info.models.profile_photo_upload_path, validators=[info.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(help_text='Upload a PDF file (max 5MB)', upload_to=info.models.resume_upload_path, validators=[info.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one resume can be active at a time'),
        ),
    ]
