# Generated by Django 5.0 on 2023-12-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_profilelink_delete_linkedin_delete_twitterx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'GitHub',
            },
        ),
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'LinkedIn',
            },
        ),
        migrations.CreateModel(
            name='TwitterX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Twitter/X',
            },
        ),
        migrations.DeleteModel(
            name='ProfileLink',
        ),
    ]
